/// \file pybind_mkdoc.h
///
/// Collect the shenanigans needed to use pybind11_mkdoc
/// to extract Python documentation from the C++ docstrings
/// if available.
///
/// Provides a placeholder DOC() macro
/// in the case where pybind11_mkdoc isn't available.

#ifndef SUPERA_PYBIND_MKDOC_H
#define SUPERA_PYBIND_MKDOC_H

#ifdef USE_MKDOC_DOCSTRINGS
// note that the docstrings.h is autogenerated by pybind11_mkdoc,
// which is run by CMake.
// see the CMakeLists.txt in /src.
#include "docstrings.h"
#else
#define DOC(...) ""
#endif


#endif //SUPERA_PYBIND_MKDOC_H
