
#include "process_pybind.h"

#ifdef USE_MKDOC_DOCSTRINGS
// note that the docstrings.h is autogenerated by pybind11_mkdoc,
// which is run by CMake.
// see the CMakeLists.txt in /src.
#include "docstrings.h"
#endif

#include "Driver.h"

void init_process(pybind11::module& m)
{
  pybind11::class_<supera::Driver>(m, "Driver", DOC(supera, Driver))
      .def("ConfigureBBoxAlgorithm", &supera::Driver::ConfigureBBoxAlgorithm, DOC(supera, Driver, ConfigureBBoxAlgorithm))
      .def("ConfigureLabelAlgorithm", &supera::Driver::ConfigureLabelAlgorithm, DOC(supera, Driver, ConfigureLabelAlgorithm))
      .def("Reset", &supera::Driver::Reset, DOC(supera, Driver, Reset))
      .def("GenerateImageMeta", &supera::Driver::GenerateImageMeta, DOC(supera, Driver, GenerateImageMeta))
      .def("GenerateLabel", &supera::Driver::GenerateLabel, DOC(supera, Driver, GenerateLabel))
      .def("Label", &supera::Driver::Label, DOC(supera, Driver, Label))
      .def("Meta", &supera::Driver::Meta, DOC(supera, Driver, Meta));

}
